resources:
 - name: start_all
   type: PropertyBag
   configuration:
     hello: world
 
pipelines:
 - name: pagerduty_notifications
   configuration:
     environmentVariables:
       readOnly:
         myRoutingKey: 8c22b13ccaa04da79a9952761248c337
   steps:
     - name: ps_pagerduty_success
       type: PowerShell
       configuration:
         nodePool: static-win
         inputResources:
           - name: start_all
         integrations:
           - name: pagerduty
       execution:
         onExecute:
           -  send_notification pagerduty -routingkey $myRoutingKey -text "hello world from powershell run number $run_number" 
         //  -  send_notification pagerduty -routingkey $myRoutingKey 
         //  -  send_notification pagerduty -routingkey badkey -text "bad routing key" 
         //  -  send_notification pagerduty -text "no routing key" 
         //  -  send_notification pagerduty 
 
     - name: bash_pagerduty_success
       type: Bash
       configuration:
         inputResources:
           - name: start_all
         integrations:
           - name: pagerduty
       execution:
         onExecute:
           - send_notification pagerduty --routingkey $myRoutingKey --text "hello world from bash run number $run_number"
         //  - send_notification pagerduty --routingkey $myRoutingKey 
         //  - send_notification pagerduty --routingkey badkey --text "bad routing key"
         //  - send_notification pagerduty --text "no routing key"
         //  - send_notification pagerduty
